# =========================
# RUTAS BASE
# =========================
$hypr = ~/.config/hypr
$hl = $hypr/hyprland
$cConf = ~/.config/caelestia

# =========================
# VARIABLES (COLORES / TEMA)
# =========================
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# =========================
# VARIABLES DE USUARIO
# =========================
exec = mkdir -p $cConf && touch -a $cConf/hypr-vars.conf
source = $cConf/hypr-vars.conf

# =========================
# MONITORES
# =========================
# Laptop (pantalla interna)
monitor = eDP-1,1920x1080@60,0x0,1

# TV HDMI duplicando laptop
# Misma resolución base obligatoria para mirror
monitor = HDMI-A-5,1920x1080@60,0x0,1.25,mirror,eDP-1

# =========================
# CONFIGURACIÓN BASE HYPRLAND
# =========================
source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/keybinds.conf

# =========================
# CONFIGURACIÓN DE USUARIO
# =========================
exec = mkdir -p $cConf && touch -a $cConf/hypr-user.conf
source = $cConf/hypr-user.conf

# =========================
# ATAJOS PERSONALIZADOS
# =========================
bind = SUPER, P, exec, ~/.config/hypr/winP.sh

exec-once = waydroid session start
